# Generated by Django 6.0.4 on 2026-06-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPLIED_OFFER_LETTER', 'Applied for Offer Letter'), ('OFFER_LETTER_RECEIVED', 'Offer Letter Received'), ('COE_APPLIED', 'COE Applied'), ('COE_RECEIVED', 'COE Received'), ('VISA_GRANTED', 'Visa Granted'), ('REJECTED', 'Rejected')], default='NEW', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
