# Generated by Django 6.0.4 on 2026-06-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('database_size_mb', models.FloatField(blank=True, null=True)),
                ('active_connections', models.IntegerField(default=0)),
                ('query_time_ms', models.FloatField(default=0.0)),
                ('request_count_hourly', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('error_count_hourly', models.IntegerField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('memory_usage_percent', models.FloatField(default=0.0)),
                ('disk_usage_percent', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_s_timesta_200b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregatedAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_students', models.IntegerField(default=0)),
                ('new_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('verified_students', models.IntegerField(default=0)),
                ('archived_students', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('applications_approved', models.IntegerField(default=0)),
                ('applications_rejected', models.IntegerField(default=0)),
                ('applications_visa_granted', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('documents_pending', models.IntegerField(default=0)),
                ('documents_approved', models.IntegerField(default=0)),
                ('documents_rejected', models.IntegerField(default=0)),
                ('followups_pending', models.IntegerField(default=0)),
                ('followups_completed', models.IntegerField(default=0)),
                ('total_managers', models.IntegerField(default=0)),
                ('total_frontdesk', models.IntegerField(default=0)),
                ('visa_success_rate', models.FloatField(default=0.0)),
                ('student_growth_percentage', models.FloatField(default=0.0)),
                ('avg_documents_per_student', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='branches.branch')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'branch'], name='analytics_a_date_43c62c_idx'), models.Index(fields=['-date'], name='analytics_a_date_cc5b5f_idx')],
                'unique_together': {('date', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='BranchPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_students_month_end', models.IntegerField(default=0)),
                ('new_enrollments', models.IntegerField(default=0)),
                ('applications_submitted', models.IntegerField(default=0)),
                ('visas_granted', models.IntegerField(default=0)),
                ('visa_success_rate', models.FloatField(default=0.0)),
                ('avg_days_to_visa', models.IntegerField(default=0)),
                ('document_approval_rate', models.FloatField(default=0.0)),
                ('avg_students_per_staff', models.FloatField(default=0.0)),
                ('staff_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('rank_among_branches', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='branches.branch')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month', 'branch'], name='analytics_b_month_6d4b24_idx'), models.Index(fields=['-month'], name='analytics_b_month_479c84_idx')],
                'unique_together': {('month', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='DetailedActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_VERIFY', 'Student Verified'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_APPROVE', 'Document Approved'), ('DOCUMENT_REJECT', 'Document Rejected'), ('DOCUMENT_DELETE', 'Document Deleted'), ('APPLICATION_CREATE', 'Application Created'), ('APPLICATION_UPDATE', 'Application Status Updated'), ('FOLLOWUP_CREATE', 'Follow-up Created'), ('FOLLOWUP_COMPLETE', 'Follow-up Completed'), ('BRANCH_CREATE', 'Branch Created'), ('BRANCH_UPDATE', 'Branch Updated'), ('BRANCH_DEACTIVATE', 'Branch Deactivated'), ('STAFF_ASSIGN', 'Staff Assigned'), ('PERMISSION_CHANGE', 'User Permission Changed'), ('SYSTEM_ERROR', 'System Error'), ('DATA_EXPORT', 'Data Exported'), ('BULK_ACTION', 'Bulk Action Performed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('changes', models.JSONField(blank=True, help_text='What changed (before/after)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='branches.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_d_user_id_831874_idx'), models.Index(fields=['branch', '-created_at'], name='analytics_d_branch__30fe50_idx'), models.Index(fields=['action', '-created_at'], name='analytics_d_action_945a9f_idx'), models.Index(fields=['created_at'], name='analytics_d_created_70df52_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('login_count', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('total_actions', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('students_processed', models.IntegerField(default=0)),
                ('documents_reviewed', models.IntegerField(default=0)),
                ('followups_completed', models.IntegerField(default=0)),
                ('average_response_time_hours', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_u_user_id_8b8eec_idx'), models.Index(fields=['branch', '-date'], name='analytics_u_branch__d050cf_idx')],
                'unique_together': {('date', 'user')},
            },
        ),
    ]
